### PR TITLE
added functions to convert to/from property arrays + readme addon

### PR DESCRIPTION
**Pull request by paulbalomiri**

### CODE REVIEW

**Comment by marklagendijk** [comment]
What is the use case for this method?

**Comment by paulbalomiri** [comment]
Hi, the best independent (as in not dependent on `Meteor` specific projects i'm using) is call path customization.

First some general consistency arguments
* The `"\\"` escape sequence it is not as trivial as a `string.split('.')` if you wanted to map a stringified path to it's elements 
* ` _.deepEscapePropertyName` is there without the corresponding `unescape`
* the corresponding `unescape` is actually not of much use, as the splitting of a path is the actual problem(not the decoding once you know where each segment starts)
*  Generally speaking while the lib user is made aware of the possibility to supply arguments interchangeably in the array/escaped string format, he has no way to make the conversion himself.
* The string version of a property path might be used in itself as an object property (see below).

Now here is some real usecase. Suppose you have this structure:
```
{a: [1,2,3,4,5]} 
```
* right now, i'm using $ to represent any element. Thus `a.$` is resolved into `a.0`...`a.4`. In order to so this i need to be able to analyse each segment of a given path, regardless of the form it was supplied in.
* One could also implement `a.__sum__` to have something more obviously useful
* Now i'm not proposing to add all sorts of crazy things to the lib, i'm just arguing that in itself the encode/decode path functions should be public.
Well, i'm using this in meteor for , amongst other things, implementing schema validation as in
[simple-schema](https://github.com/aldeed/meteor-simple-schema).

Also i'm, implementing some algorithms for publishing  linked object sets using  `Meteor.publish` functions, for which i plan to release some packages.

As for the default argument in _.deepGet:
* I'm not quite sure that actually setting the default argument is such a good idea. I'm not saying its bad either, but i think a default argument to a get function has obvious usecases. If you want i can provide a patch without that.

**Comment by marklagendijk** [comment]
Could you clean up the commits by squashing them all into 1, and rebase based on the latest changes? When you do that I can review your changes properly, and see if they are ready to be merged in.

**Comment by paulbalomiri** [comment]
yes, and i also fopund a bug in my code. Is next week monday ok?

2015-02-25 19:11 GMT-05:00 Mark Lagendijk <notifications@github.com>:

> Could you clean up the commits by squashing them all into 1, and rebase
> based on the latest changes? When you do that I can review your changes
> properly, and see if they are ready to be merged in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marklagendijk/lodash-deep/pull/34#issuecomment-76092006>
> .
>



-- 
paulbalomiri@gmail.com

**Comment by marklagendijk** [comment]
Sure, no problem. Thanks for your contribution :).

**Comment by paulbalomiri** [comment]
one more thing: What a bout a default argument to deepGet? 
Do you want that in, and if yes shall it 

* just return the default argument
* return and set the default argument?

**Comment by marklagendijk** [comment]
Hmm, I don't think that this should be added to deepGet. If you want to get a default value if there is nothing you could just write `var myValue = _.deepGet(collection, 'property.path') || 'defaultValue';`. However, it might be useful to implement a `_.deepSetDefault` method, which would set a default value, if none exists. 

``` javascript
// before
if(!_.deepGet(collection, 'property.path')){
  _.deepSet(collection, 'property.path', 'defaultValue');
}

// after
_.deepSetDefault(collection, 'property.path', 'defaultValue');
```
I think I will implement and add this method today. Thanks for the inspiration :).

**Comment by paulbalomiri** [comment]
Well, a `deepSetDefault` is an inferior use case to `deepGetDefault`, i would argue. Mostly what you do is iterate over potentially unset values. a deepGetDefault would spare you the combination 
```
unless  val=deepGet path
  val=some_initial_cheap_value
  deepSet path val
```
and make it into
```
val= deepGetDefault path some_initial_cheap_value
```

`deepSetDefault` would make the initial statement a 2-liner, but you would still need the 
`deepSetDefault/deepGet` combo

Basically i think what is missing  in the Get/Set pairs is :

* `deepGet` (or version thereof) which 
  * sets a default value
* `deepSet` (or version thereof) which
  * returns the old value

I just wanted to share these thoughts if you are going to code today.

**Comment by paulbalomiri** [comment]
Hi, i-ve done some in console testing, and i came up with this variant, should you decide to construct an array.

```
function (key){var arr=[]; arr[key]=0; return arr.length>0; }
```
regarding performance:
* sparse arrays are *must* for this
  * the initialization of array[key] (otherwhise a[5e10] would quickly eatup all memory)

I read your last answer right now. Would you test the above function ? It would guarantee that the key
is generated exactly as in the underlying implementation.

**Comment by marklagendijk** [comment]
The solution I implemented is [_.deepDefault](https://github.com/marklagendijk/lodash-deep#_deepdefaultcollection-propertypath-defaultvalue). I think this makes most sense, and hope that you will like it :).

**Comment by paulbalomiri** [comment]
Ok,, thx & i will make a proper diff for the string part in the weekend.

**Comment by marklagendijk** [comment]
@paulbalomiri when you get time to do this, please open a new pull request against the canary branch.

**Pull request closed without merging**
