### PR TITLE
allow overriding lodash

### PR DESCRIPTION
**Pull request by spalger**
Since lodash-deep requires lodash, it declares a dependency for the module id `'lodash'` (which makes total sense) but in my project the module id `'lodash'` maps to [our mixins module](https://github.com/elasticsearch/kibana/blob/master/src/kibana/utils/_mixins.js) and not lodash proper. In order to use lodash-deep in our project, we have been using a fork that replaces the [required module id](https://github.com/spenceralger/lodash-deep/commit/5390880db16a15aa8a5ed9ebd156da471dc340a4).

It would be great if lodash-deep could export a function that takes `_` and mixes in the lodash-deep methods.

This pr moves the source code into three files in `src/` and adds a gulp task that combines them into two files: `lodash-deep.js` (same as it is today) and `factory.js` which just exports a factory function that takes an instance of lodash and mixes in lodash-deep.

For users who have similar restrictions, they would:
```js
var _ = require('lodash');
require('lodash-deep/factory')(_);
```

### CODE REVIEW

**Comment by marklagendijk** [comment]
I'm sorry, but this does not seem to make much sense to me. Why do you want to use `lodash` as a module id for something which is not `lodash`? This will only confuse people reading your code.
Wouldn't it be better to just call that module something like `custom-lodash`?

**Comment by spenceralger** [comment]
I understand that it was probably a bad decision but I think it still makes sense.

Use case 2: you want to use lodashDeep but don't want to include all of lodash as a dep (this is why packages like lodash-merge are available). In order to use lodash deep you could mimic the parts of the lodash api required by lodash-deep and pass that into the factory.

Use case 3: you want to use the lodash-node package rather than the lodash package

Use case 4: you want to use lodash/lodash.underscore.js

I think you get the point...

**Comment by marklagendijk** [comment]
I'm sorry but I don't think these usecases are common enough to justify the extra complexity this adds.
For your specific usecase I would recommend to rename your mixins module to something like `lodash-with-mixins` and require that instead.

**Comment by spalger** [comment]
Fair enough :smile:

**Pull request closed without merging**
